apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../apps/nginx

kind: Kustomization
metadata:
  name: nginx-app
  namespace: flux-system
spec:
  interval: 1m
  path: ./apps/nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: default

